### PR TITLE
fixed carousel to slide elegantly

### PR DESCRIPTION
**Pull request by young-min-ko**
thumbnail can be used for navigation

need to work on style selector

### CODE REVIEW

**Review by zrendy — APPROVED** [review]
@young-min-ko WOW LOOKS GREAT, the carousel so smooth

**Comment by young-min-ko** [comment]
> @young-min-ko WOW LOOKS GREAT, the carousel so smooth

i know right?

**Review by oscardong0813 — APPROVED** [review]
WOWOWOWOWOW cool carousel

**Comment by shethinksnyc** [comment]
Look good Young!

**Review by shethinksnyc — COMMENTED** [review]
Looks great Young!!

**Review by shethinksnyc — APPROVED** [review]

**Pull request merged**
