### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by zrendy**
@oscardong0813 @shethinksnyc @young-min-ko 
HEY GUYS CHECKOUT MY AWESOME README!

### CODE REVIEW

**Comment by young-min-ko** [comment]
@zrendy 
hey I just read the edit it looks good so far

**Comment by oscardong0813** [comment]
@zrendy  coooool

**Comment by shethinksnyc** [comment]
Looks good Rendy!

**Review by oscardong0813 — CHANGES_REQUESTED** [review]
Hey Rendy, that was interesting, hmmmm...

**Review by oscardong0813 — APPROVED** [review]

**Review by shethinksnyc — COMMENTED** [review]
V.1 of Readme looks goof Rendy!

**Pull request merged**
